# Generated by Django 5.2.4 on 2025-07-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedling_app', '0002_qrcode_remove_household_household_qr_id_dea80f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agroevent',
            name='AgroEvent_type_d30d83_idx',
        ),
        migrations.RemoveField(
            model_name='agroevent',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='agroevent',
            name='type',
        ),
        migrations.AddField(
            model_name='agroevent',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agro_events', to='seedling_app.statustypes'),
        ),
        migrations.AddIndex(
            model_name='agroevent',
            index=models.Index(fields=['status'], name='AgroEvent_status__de79ac_idx'),
        ),
    ]
