# Generated by Django 5.2.4 on 2025-07-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedling_app', '0003_remove_agroevent_agroevent_type_d30d83_idx_and_more'),
    ]

    operations = [
    ]
