# Generated by Django 5.2.3 on 2025-06-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedling_app', '0004_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
